# Generated by Django 2.2.3 on 2020-01-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_mode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedsong',
            old_name='song_name',
            new_name='name',
        ),
    ]
