# Generated by Django 2.2.3 on 2020-01-26 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party_mode', '0002_auto_20200125_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedsong',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
